{% set name = "modelmimic" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/modelmimic-{{ version }}.tar.gz
  sha256: ed8be1f21c05f06af0e1c6b785aa2c5c19fc9e7fe35a12a63645a4dd72ad9a40

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.10
    - numpy
    - xarray
    - netcdf4
    - pandas
    - toml

test:
  imports:
    - modelmimic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LIVVkit/modelmimic
  summary: Generate model-like data, _mimic_ the output of various CIME tests.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mkstratos
